# Generated by Django 2.2 on 2022-09-30 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220930_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('unitPrice', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('imgPath', models.CharField(default='', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
