# Generated by Django 2.2 on 2022-10-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='attrValueList',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='attrList',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
