# Generated by Django 2.2 on 2022-10-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstatus',
            name='didReview',
            field=models.BooleanField(default=False),
        ),
    ]
