# Generated by Django 2.2 on 2022-10-07 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0013_reviewstatus_didreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='detail',
            field=models.TextField(default=''),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product')},
        ),
    ]
