# Generated by Django 2.2 on 2022-10-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20221008_0053'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reviewstatus',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique1'),
        ),
        migrations.AlterModelTable(
            name='reviewstatus',
            table='product_reviewstatus',
        ),
    ]
