# Generated by Django 2.2 on 2022-10-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20221008_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
