# Generated by Django 2.2 on 2022-10-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_review_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='totalReview',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='totalStar',
            field=models.IntegerField(default=0),
        ),
    ]
