# Generated by Django 2.2 on 2022-10-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='imgPath',
            field=models.CharField(default='', max_length=255),
        ),
    ]
