# Generated by Django 2.2 on 2022-10-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser_imgpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
