# Generated by Django 2.2 on 2022-10-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchaseType',
            field=models.CharField(default='COD', max_length=255),
        ),
    ]
