# Generated by Django 4.1.3 on 2022-11-10 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestSupport',
        ),
    ]
